---
id: Kolab_FreeBusy
name: Kolab_FreeBusy
full: Kolab application providing free/busy information
description: |
  Free/busy information for the
  users of a Kolab server. A Kolab client changing calendar data in an
  IMAP folder is required to call the triggering script provided within
  this package via HTTP. This will refresh the cache maintained by this
  package with partial free/busy data. This partial data sets are
  finally combined to the complete free/busy information once a client
  requests this data for a particular user.
list: dev
type: library
authors:
  -
    name: Gunnar Wrobel
    user: wrobel
    email: p@rdus.de
    active: true
    role: lead
version:
  release: 1.0.0alpha1
  api: 1.0.0
state:
  release: beta
  api: beta
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Kolab_Format: ^2
      pear.horde.org/Horde_Kolab_Server: ^2
      pear.horde.org/Horde_Kolab_Storage: ^2
      pear.horde.org/Horde_Icalendar: ^2
      pear.horde.org/Horde_Date: ^2
      pear.horde.org/Horde_Translation: ^2.2
      pear.horde.org/Horde_Util: ^2
  optional:
    pear:
      pear.horde.org/Horde_Test: ^2.1
